version: '3.7'
services:
  database:
    image: andrestaffoli/sortarray-database:e057591ccbc0402f955a1448eb2abfde1e4b86e5
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - default
    restart: on-failure
    volumes:
      - percona-data:/var/lib/mysql

  sortarray:
    image: andrestaffoli/sortarray-sortarray:e057591ccbc0402f955a1448eb2abfde1e4b86e5
    ports:
      - "8080:8080"
    networks:
      - default
    restart: on-failure
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8080"]
    links:
      - database

  gatewayapp:
    environment:
      LOGLEVEL: "INFO"
    image: andrestaffoli/sortarray-gatewayapp:e057591ccbc0402f955a1448eb2abfde1e4b86e5
    networks:
      - default
    depends_on:
      sortarray:
        condition: service_healthy
    restart: on-failure

networks:
   default:
     driver: bridge

volumes:
  percona-data:
