version: '3.7'
services:
  database:
    image: andrestaffoli/sortarray-database:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - default
    restart: on-failure
    volumes:
      - percona-data:/var/lib/mysql

  sortarray:
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://database:3306/array"
    image: andrestaffoli/sortarray-sortarray:latest
    ports:
      - "8080:8080"
    networks:
      - default
    restart: on-failure
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8080"]
    links:
      - database

  gatewayapp:
    environment:
      LOGLEVEL: "INFO"
    image: andrestaffoli/sortarray-gatewayapp:latest
    networks:
      - default
    depends_on:
      sortarray:
        condition: service_healthy
    restart: on-failure

networks:
   default:
     driver: bridge

volumes:
  percona-data: