version: '3.7'
services:
  database:
    build:
      context: service/percona
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: on-failure
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - percona-data:/var/lib/mysql

  sortarray:
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://database:3306/array"
    build:
      context: sortArray/
      args:
        DEPENDENCY: build/dependency
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - database
    restart: on-failure
    links:
      - database

  gatewayapp:
    build:
      context: gatewayApp/
    networks:
      - default
    depends_on:
      sortarray:
        condition: service_started
      database:
        condition: service_started
    restart: on-failure

networks:
   default:
     driver: bridge

volumes:
  percona-data:
