apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sortarray-database
  labels:
    app: sortarray
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sortarray
        octopusexport: OctopusExport
    spec:
      containers:
        - name: database
          image: 'andrestaffoli/sortarray-database:latest'
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'password'
          ports:
            - name: endpoint
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: database-volume
              mountPath: '/var/lib/mysql'
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: mysql-pv-claim
