apiVersion: apps/v1
kind: Deployment
metadata:
  name: sortarray-gatewayapp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: gatewayapp
  template:
    metadata:
      labels:
        component: gatewayapp
    spec:
      containers:
        - name: sortarray-gatewayapp
          image: 'andrestaffoli/sortarray-gatewayapp:{{ .Values.general.tag }}'
