apiVersion: v1
kind: Service
metadata:
  name: gatewayapp
spec:
  selector:
    component: gatewayapp
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sortarray-gatewayapp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: gatewayapp
  template:
    metadata:
      labels:
        component: gatewayapp
    spec:
      containers:
        - name: gatewayapp
          image: 'andrestaffoli/sortarray-gatewayapp:{{ .Values.general.tag }}'
