apiVersion: v1
kind: Service
metadata:
  name: sortarray
spec:
  selector:
    component: sortarray
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sortarray-sortarray
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: sortarray
  template:
    metadata:
      labels:
        component: sortarray
    spec:
      containers:
        - name: sortarray
          image: 'andrestaffoli/sortarray-sortarray:{{ .Values.general.tag }}'
          ports:
            - name: sortarray-port
              containerPort: 8080
              protocol: TCP

