name: gatewayapp-action

on:
  pull_request:

jobs:
  build-database:
    runs-on: ubuntu-latest

    steps:
      - name: export commit_hash
        run: echo "COMMIT_HASH = $(git rev-parse HEAD)" >> &GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t staffolis/sortarray:database-${{ env.COMMIT_HASH }} service/percona

      - name: Login docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push staffolis/sortarray:database-$COMMIT_HASH

  build-sortarray:
    runs-on: ubuntu-latest

    steps:
      - name: export commit_hash
        env:
          COMMIT_HASH: $(git rev-parse HEAD)

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: cd sortArray && chmod +x ./gradlew

      - name: Run database
        run: docker run -d -e MYSQL_ROOT_PASSWORD=password --publish 3306:3306 --network bridge -v percona-data:/var/lib/mysql staffolis/sortarray:database

      - name: Gradlew build
        run: cd sortArray && ./gradlew build

      - name: move dependency
        run: mkdir -p sortArray/build/dependency

      - name: extract dependency
        run: cd sortArray/build/dependency && $JAVA_HOME/bin/jar -xf ../libs/*.jar

      - name: Docker build
        run: docker build -t staffolis/sortarray:sortarray-$COMMIT_HASH sortArray/.

      - name: Login docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push staffolis/sortarray:sortarray-$COMMIT_HASH

  build-gatewayapp:
    runs-on: ubuntu-latest

    steps:
      - name: export commit_hash
        env:
          COMMIT_HASH: $(git rev-parse HEAD)

      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t staffolis/sortarray:gatewayapp-$COMMIT_HASH gatewayApp/.

      - name: Login docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push staffolis/sortarray:gatewayapp-$COMMIT_HASH
