name: gatewayapp-action

on:
  pull_request:

jobs:
  build-database:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t andrestaffoli/sortarray-database:${{ github.event.pull_request.head.sha }} service/percona

      - name: Login docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push andrestaffoli/sortarray-database:${{ github.event.pull_request.head.sha }}

  build-sortarray:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Docker build
        run: docker build -t andrestaffoli/sortarray-sortarray:${{ github.event.pull_request.head.sha }} sortArray/.

      - name: Docker tag
        run: docker tag andrestaffoli/sortarray-sortarray:${{ github.event.pull_request.head.sha }} andrestaffoli/sortarray-sortarray:latest

      - name: Login docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker image push --all-tags andrestaffoli/sortarray-sortarray
        
  build-gatewayapp:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t andrestaffoli/sortarray-gatewayapp:${{ github.event.pull_request.head.sha }} gatewayApp/.

      - name: Docker tag
        run: docker tag andrestaffoli/sortarray-gatewayapp:${{ github.event.pull_request.head.sha }} andrestaffoli/sortarray-gatewayapp:latest

      - name: Login docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker image push --all-tags andrestaffoli/sortarray-gatewayapp
