name: Database build and push

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: service/percona/.
          push: true
          tags: staffolis/sortarray/database:latest
