name: gatewayapp-action

on:
  push:
    branches:
      - feature/build-and-push-gatewayapp

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: check out code

    - name: docker build
      run: docker build -t staffolis/sortarray:gatewayapp gatewayApp/.

    - uses: docker/login-action@v1
      name: docker login
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: push image
      run: docker push staffolis/sortarray:gatewayapp
