name: tag-images

on:
  push:
    branches:
      - develop
      - master

jobs:
  push-to-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t andrestaffoli/sortarray-database:${GITHUB_REF##*/} service/percona

      - name: Login docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker image push --all-tags andrestaffoli/sortarray-database

  build-sortarray:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Docker build
        run: docker build -t andrestaffoli/sortarray-sortarray:${GITHUB_REF##*/} sortArray/.

      - name: Login docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker image push --all-tags andrestaffoli/sortarray-sortarray

  build-gatewayapp:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t andrestaffoli/sortarray-gatewayapp:${GITHUB_REF##*/} gatewayApp/.

      - name: Login docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker image push --all-tags andrestaffoli/sortarray-gatewayapp
